### ISSUE TITLE
Thunkable Example Projects No Longer Live

### ISSUE THREAD

**Issue by MrMazzone** [thunkable/webviewer-extension#2]
When I click on your Thunkable Example projects, it cannot open the project.  Would love to see a working example.

**Comment by josmas** [comment]
Hey @MrMazzone do you mean [sample apps](https://docs.thunkable.com/sample-apps)?
Or the tutorials inside the app? Or the tutorials inside the designer?

**Comment by MrMazzone** [comment]
Hi @josmas I am speaking specifically about the webviewer extension.  There are two example projects on the README.  The Thunkable links no longer work.
![image](https://user-images.githubusercontent.com/40954645/88802555-38a7f200-d179-11ea-930f-e12bc0aed7fe.png)

This is what I see when I try to open those example projects:
![image](https://user-images.githubusercontent.com/40954645/88802668-62f9af80-d179-11ea-9e76-3336d7b66c7f.png)

**Comment by josmas** [comment]
oh, apologies @MrMazzone I didn't realise that you reported this on a different repo!

I'll ask if we've removed those two projects for any particular reason. Thanks for the report.

**Comment by MrMazzone** [comment]
@josmas No problem!  That is exactly what I figured happened.

**Comment by pmwthunkable** [comment]
The example projects should be working again.

**Comment by MrMazzone** [comment]
They are!  Perfect! thank you
